### ISSUE TITLE
Where can I purchase one of 16SoundsUSB?

### ISSUE THREAD

**Issue by jamesshao8** [introlab/16SoundsUSB#1]
This is probably rather an enquiry than an issue. I recently tried odas/odas_web with respeaker mic array v1.0 and v2.0. I am quite impressed by your project.

I want to improve the angle of separation, so that I can distinguish 2 sources in closer angles. I believe this 16 array would produce better result. So could you direct me some place that I can buy this 16 channel device?

Thanks.

**Comment by doumdi** [comment]
Please email Prof. [François Michaud](mailto:francois.michaud@usherbrooke.ca) for a quote.

Thanks!
